version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: hrms_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Abhi@7050
      MYSQL_DATABASE: new_hrms
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pAbhi@7050"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hrms_container
    command: >
      sh -c "until nc -z db 3306;
             do echo '⏳ Waiting for DB...';
             sleep 2;
             done;
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_NAME: new_hrms
      DB_USER: root
      DB_PASSWORD: Abhi@7050
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  db_data:
 



 