# Generated by Django 5.2.5 on 2025-09-03 08:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_role', models.CharField(blank=True, max_length=100)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('activity_text', models.TextField()),
                ('project_name', models.CharField(blank=True, max_length=100)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Address', models.TextField()),
                ('Resume', models.ImageField(upload_to='media/Resume')),
                ('Gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=15)),
                ('Department', models.CharField(choices=[('UI/UX', 'UI/UX'), ('Development', 'Development'), ('Management', 'Management'), ('HR', 'HR'), ('Testing', 'Testing'), ('Marketing', 'Marketing')], max_length=40)),
                ('Experince', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feature_image', models.ImageField(upload_to='media/Employee')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthdaydate', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('department', models.CharField(choices=[('UI/UX', 'UI/UX'), ('Development', 'Development'), ('Management', 'Management'), ('HR', 'HR'), ('Testing', 'Testing'), ('Marketing', 'Marketing')], default='Development', max_length=100)),
                ('position', models.CharField(choices=[('Manager', 'Manager'), ('Team Lead', 'Team Lead'), ('Developer', 'Developer'), ('Designer', 'Designer'), ('QA Engineer', 'QA Engineer'), ('HR', 'HR'), ('Intern', 'Intern'), ('Other', 'Other')], default='Developer', max_length=100)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('Educations', models.CharField(choices=[('10TH', '10TH'), ('12TH', '12TH'), ('BACHELOR', 'BACHELOR'), ('MASTER', 'MASTER'), ('PHD', 'PHD'), ('OTHER', 'OTHER'), ('DIPLOMA', 'DIPLOMA'), ('CERTIFICATION', 'CERTIFICATION')], default='BACHELOR', max_length=100)),
                ('Address', models.CharField(choices=[('jharkhand', 'jharhand'), ('Bihar', 'Bihar'), ('UP', 'UP'), ('MP', 'MP'), ('Rajasthan', 'Rajasthan'), ('Punjab', 'Punjab'), ('Haryana', 'Haryana'), ('Delhi', 'Delhi'), ('Kashmir', 'Kashmir'), ('Goa', 'Goa'), ('Kerala', 'Kerala'), ('Tamil Nadu', 'Tamil Nadu'), ('Karnataka', 'Karnataka'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Telangana', 'Telangana'), ('Odisha', 'Odisha'), ('West Bengal', 'West Bengal'), ('Assam', 'Assam'), ('North East', 'North East'), ('Other', 'Other')], default='Other', max_length=150)),
                ('Country', models.CharField(default='India', max_length=100)),
                ('Company', models.CharField(default='ABC Pvt Ltd', max_length=100)),
                ('performance_score', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('punch_in_time', models.TimeField()),
                ('punch_out_time', models.TimeField(blank=True, null=True)),
                ('production_hours', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_public', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_leaves', models.IntegerField()),
                ('taken', models.IntegerField()),
                ('absent', models.IntegerField()),
                ('request', models.IntegerField()),
                ('worked_days', models.IntegerField()),
                ('loss_of_pay', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('target', models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee')], default='Employee', max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('some_date', models.DateField(default=datetime.date.today)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_meeting', models.CharField(max_length=200)),
                ('date_meeting', models.DateTimeField(blank=True, null=True)),
                ('time_meeting', models.TimeField(blank=True, null=True)),
                ('Department', models.CharField(max_length=200)),
                ('participants', models.ManyToManyField(to='App.employee')),
            ],
        ),
        migrations.CreateModel(
            name='MySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('JavaScript', 'JavaScript'), ('React', 'React'), ('Node.js', 'Node.js'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Java', 'Java'), ('C++', 'C++'), ('C#', 'C#'), ('Ruby', 'Ruby'), ('PHP', 'PHP'), ('Swift', 'Swift'), ('Kotlin', 'Kotlin'), ('Go', 'Go'), ('SQL', 'SQL'), ('NoSQL', 'NoSQL'), ('AWS', 'AWS'), ('Azure', 'Azure'), ('Docker', 'Docker'), ('Kubernetes', 'Kubernetes'), ('Machine Learning', 'Machine Learning'), ('Data Science', 'Data Science'), ('DevOps', 'DevOps'), ('UI/UX Design', 'UI/UX Design'), ('Project Management', 'Project Management'), ('Agile Methodologies', 'Agile Methodologies'), ('Scrum', 'Scrum'), ('Communication Skills', 'Communication Skills'), ('Problem Solving', 'Problem Solving'), ('Leadership', 'Leadership'), ('Time Management', 'Time Management'), ('Critical Thinking', 'Critical Thinking'), ('Collaboration', 'Collaboration'), ('Adaptability', 'Adaptability'), ('Creativity', 'Creativity'), ('Emotional Intelligence', 'Emotional Intelligence'), ('Conflict Resolution', 'Conflict Resolution'), ('Decision Making', 'Decision Making'), ('Networking', 'Networking'), ('Public Speaking', 'Public Speaking'), ('Writing Skills', 'Writing Skills'), ('Other', 'Other')], max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('percentage', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('Recent', 'Recent'), ('Latest', 'Latest')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipients', models.ManyToManyField(related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('month', models.CharField(default='January', max_length=20)),
                ('year', models.IntegerField(default=2025)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('hour', models.IntegerField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('On Hold', '⏸ On Hold'), ('Completed', '✅ Completed'), ('Incomplete', '❌ Incomplete'), ('Pending', '⏳ Pending'), ('Received', '📥 Received'), ('In Progress', '⏳ In Progress')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assign_to_all', models.BooleanField(default=False)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
